---
title: "Lab 05 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Lily Botha"
date: "02/17/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox) 
library(readr)
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
dn <- read_csv("https://github.com/DataScience4Psych/DataScience4Psych/raw/main/data/raw-data/dennys.csv")
lq <- read_csv("https://github.com/DataScience4Psych/DataScience4Psych/raw/main/data/raw-data/laquinta.csv")
```

### Exercise 1

There are 3 Denny's locations in Alaska. 

```{r dn-ak}
dn_ak <- dn %>%
  filter(state == "AK")
nrow(dn_ak)
```

There are 2 La Quinta locations in Alaska. 

```{r lq-ak}
lq_ak <- lq %>% 
  filter(state == "AK")
nrow(lq_ak)
```

### Exercise 2

There are 6 pairings between all Denny's and all La Quinta locations in Alaska, so we need to calculate 6 distances. 

```{r dn-lq-ak-pairings}
nrow(dn_ak) * nrow(lq_ak)
```

### Exercise 3

```{r}
dn_lq_ak <- full_join(dn_ak, lq_ak, #use full_join to keep all rows and columns from both dfs
  by = "state"
)
dn_lq_ak
```


### Exercise 4

...

### Exercise 5

...

### Exercise 6

...

Add exercise headings as needed.
